### ISSUE TITLE
[FEATURE] Google OAuth in Django

### ISSUE THREAD

**Issue by h0nz1n** [lindamotejl/Secure-Application-Dev#11]
Implementation of Google OAuth into Django framework.

## Detailed Description

We want to allow users to log in via their existing Google accounts. This issue will cover implementation of this functionality into Django framework used in back-end.

## Possible Implementation

https://devdelly.com/django-google-oauth/
https://python-social-auth.readthedocs.io/en/latest/index.html
https://www.section.io/engineering-education/django-google-oauth/

## Tasks

- [x] Research the implementation guides
- [x] Implement the OAuth based authentication
- [x] Test correct functionality
