### ISSUE TITLE
[TASK] Configuring basic Template layer in Django

### ISSUE THREAD

**Issue by h0nz1n** [lindamotejl/Secure-Application-Dev#14]
## Detailed Description of task
This issue covers the work on the template layer in the Django framework using the work done by the frontend team.

## Tasks
- [x] Configure the basic HTML wireframe to be displayed properly
- [x] Implement design and dynamic functionality (CSS/JS)
- [x] Explain inner working of the Django template layer to the rest of the team
