### ISSUE TITLE
[TASK] Implementing the Yelp API wrapper application in Django

### ISSUE THREAD

**Issue by h0nz1n** [lindamotejl/Secure-Application-Dev#15]
## Detailed Description of task
This task documents the implementation of the already tested Yelp API wrapper code into a Django application.

## Context
This application functionality will take care of the requests towards the Yelp Fusion API v3.

### API documentation:
https://www.yelp.com/developers/documentation/v3/get_started

### API endpoint registration details:
**Client ID**
eVq0jyasKlr3BhFqiF40Zw

**API Key**
DvzFItmL9dErFb03EHKQD9igDzRc9Z7dA0npAaxKWWMyM8LzRr_fpAxKMeErHXItKoVHJQjMwWf0YbroA8jLztf8PZul0NWH7wxG9gzJNCExv5DDphZd7DrbCtNHYHYx

## Tasks
- [x] Prepare a API request script
- [x] Test saving the API response in MongoDB
- [ ] Display formatted API response on the front-end template layer

**Comment by h0nz1n** [comment]
I have failed implementing displaying of the api_wrapper.py output on the template layer due to lack of Django framework inner working knowledge.
