### ISSUE TITLE
[TASK] Configuring Model layer in Django

### ISSUE THREAD

**Issue by h0nz1n** [lindamotejl/Secure-Application-Dev#16]
## Detailed Description of task
This issue covers designing of the model layer in the Django framework. The project backend is using MongoDB Atlas database service.

Docs: https://www.djongomapper.com/using-django-with-mongodb-data-fields/

## Context
It is necessary to store the user (and possibly also restaurant) data in the Foodle application's database. User data will be used for storing user's session information - applied filters, personal preferences and history.

Storing restaurant data is currently not considered necessary, as the API wrapper output can be rendered directly on frontend.

## Tasks
- [x] Set up local MongoDB instance
- [x] Test correct functionality with Django
- [x] Configure MongoDB Atlas cluster
- [x] Test successful database migration
- [ ] Configure the model layer based on existing DB collections created by Django
