### ISSUE TITLE
[FEATURE] Sign In & Sign Up page

### ISSUE THREAD

**Issue by h0nz1n** [lindamotejl/Secure-Application-Dev#20]
## Detailed Description

This issue will document development of separate Sign In page offering local account login or Google account login (implemented in #11) and development of local account creation Sign Up page.

## Context
It is necessary to offer multiple sign in options for the user. As a minimum, local account and Google account sign-in options need to be implemented.

## Possible Implementation

WIP

## Tasks

- [x] Design simple Sign In page
- [x] Implement local account and Google account login options
- [x] Design simple Sign Up (local account creation) page
