### ISSUE TITLE
[TASK] Testing local Heroku build

### ISSUE THREAD

**Issue by h0nz1n** [lindamotejl/Secure-Application-Dev#23]
## Detailed Description of task

This issue will cover local build testing using Heroku CLI, before the first Foodle version is deployed on the public server.

## Tasks

- [x] Configure Django settings to use MongoDB Atlas
- [x] Test successful database migration
- [x] Update PIP requirements.txt
- [x] Test successful local build using Heroku CLI
