### ISSUE TITLE
[FEATURE] Configure Django Pytests

### ISSUE THREAD

**Issue by h0nz1n** [lindamotejl/Secure-Application-Dev#24]
## Detailed Description

This issue covers configuration of automated build tests of the Foodle application using GitHub CI pipeline. 

## Possible Implementation
pytest-django is a plugin for pytest that provides a set of useful tools for testing Django applications and projects:
https://djangostars.com/blog/django-pytest-testing/
https://pytest-django.readthedocs.io/en/latest/index.html

## Tasks

- [x] Configure GitHub workflow action for build testing
- [x] Implement basic test scripts for core Django project functionality
- [ ] Make sure the automated workflow action works as expected
