### ISSUE TITLE
[TASK] Migrating front-end code to Django

### ISSUE THREAD

**Issue by lindamotejl** [lindamotejl/Secure-Application-Dev#25]
## Detailed Description of task

Moving HTML, CSS and JS from front-end folder to the static and template folders in the src folder.

## Context

Code must be inserted into Django framework.
## Tasks

- [ ] Linda's code @lindamotejl 
- [ ] Sam's code @Sam2208 
- [ ] Anoth's code @AnothJV
