### ISSUE TITLE
[TASK]  Results page filters

### ISSUE THREAD

**Issue by lindamotejl** [lindamotejl/Secure-Application-Dev#28]
## Detailed Description of task

Filter on the left hand bar will be removed. Filtering will instead be on top of results.html 
## Context

Removing the search bar that was supposed to be on the homepage and results page is a drastic decrease in users being able to customize and filter results. Therefore placing filters on top of the results page will highlight the section of adjusting preferences.
## Tasks

- [x] Redesign on Figma
- [x] Team evaluation and input
- [x] Wireframe 
- [x] CSS and JS
- [ ] Connecting buttons with db
- [ ] Testing

**Comment by lindamotejl** [comment]
Issue could not be finished because of the incompletion of displaying the API wrapper
