### ISSUE TITLE
[RESEARCH] Restaurant selection

### ISSUE THREAD

**Issue by h0nz1n** [lindamotejl/Secure-Application-Dev#3]
Research and pick a fixed number of restaurant establishments in the PC building vicinity.

## Detailed Description

We need to create a selection of possible restaurant choices in the university building area. Multiple factors to be considered:
- cuisine variety
- vegan/vegetarian options
- web presence

## Resources
https://onemenu.cz/Home/SearchByAddress?searchText=Polsk%C3%A1+1184%2F10
https://www.tripadvisor.com/Restaurants-g274707-c26-Prague_Bohemia.html#MAPVIEW
https://www.zomato.com/praha/vinohrady-praha-2-restaurants
https://www.google.com/maps/place/Prague+College/@50.0783964,14.4377157,17z/data=!3m1!4b1!4m5!3m4!1s0x470b94900227e7c7:0x72a8f977693ca34c!8m2!3d50.078393!4d14.4399044?hl=en-US

## Tasks

- [x] Make a list of restaurants in the area
- [x] Create a limited selection
- [x] Use as output for issue #5
