### ISSUE TITLE
[TASK] FoodleBot user documentation 

### ISSUE THREAD

**Issue by anastasiia724** [lindamotejl/Secure-Application-Dev#42]
## Tasks

- [x] Setting up a virtual environment
- [x] Setting environment variables
- [x] Starting an action server, loading a trained model and talking to chatbot on the command line.
- [x] Add some demos
