### ISSUE TITLE
[RESEARCH] Web scraper

### ISSUE THREAD

**Issue by h0nz1n** [lindamotejl/Secure-Application-Dev#5]
Restaurant data need to be scraped from the web for further processing.

## Detailed Description

We need to establish methods of how we are going to be scraping the restaurant data - by using restaurant search engine's API, or scraping websites of the chosen restaurants individually.

## Possible Implementation

https://www.bestproxyreviews.com/scrapy-vs-selenium-vs-beautifulsoup-for-web-scraping/
https://www.freecodecamp.org/news/web-scraping-python-tutorial-how-to-scrape-data-from-a-website/
https://realpython.com/beautiful-soup-web-scraper-python/
https://zenscrape.com/web-scraping-with-python/
https://hackernoon.com/how-to-build-a-web-scraper-with-python-step-by-step-guide-jxkp3yum

## Tasks

- [x] Choose methodology
- [x] Choose data storage
- [x] Research existing web scraping Python libraries
- [ ] Define details of the web scraper development
