### ISSUE TITLE
[FEATURE] Yelp API wrapper

### ISSUE THREAD

**Issue by h0nz1n** [lindamotejl/Secure-Application-Dev#6]
This issue will document the details of Yelp API wrapper implementation.

## Detailed Description

The main back-end functionality of restaurant data harvesting can be achieved by automating communication with Yelp Fusion API v3.

### API documentation:
https://www.yelp.com/developers/documentation/v3/get_started

### API endpoint registration details:
**Client ID**
eVq0jyasKlr3BhFqiF40Zw

**API Key**
DvzFItmL9dErFb03EHKQD9igDzRc9Z7dA0npAaxKWWMyM8LzRr_fpAxKMeErHXItKoVHJQjMwWf0YbroA8jLztf8PZul0NWH7wxG9gzJNCExv5DDphZd7DrbCtNHYHYx

**API usage limits** - 5000 API calls per day

#### Yelp search for restaurants in the PC area:
https://www.yelp.cz/search?find_desc=&find_loc=Polsk%C3%A1%201184%2F10%2C%20120%2000%20Praha%202-Vinohrady&l=g%3A14.4273662567%2C50.0702520463%2C14.4529438019%2C50.0867762717

## Possible Implementation

https://github.com/Yelp/yelp-python (official Yelp code samples)
https://github.com/gfairchild/yelpapi
https://github.com/zehengl/ezapi-yelp

## Tasks

- [x] Test simple API queries
- [x] Asses the API responses and determine the data formatting
- [x] Find usable source code / develop API wrapper
- [x] Test wrapper outputs
