### ISSUE TITLE
[RESEARCH] Chatbot

### ISSUE THREAD

**Issue by h0nz1n** [lindamotejl/Secure-Application-Dev#7]
This issue will document the details of possible chatbot feature implementation.

## Detailed Description

It is necessary to look into possible implementation of the chatbot extra functionality. Scope the web on existing implementations, Python libraries that can be leveraged, etc.

## Possible Implementation

https://www.edureka.co/blog/how-to-make-a-chatbot-in-python/
https://data-flair.training/blogs/python-chatbot-project/
https://medium.com/analytics-vidhya/building-a-simple-chatbot-in-python-using-nltk-7c8c8215ac6e
https://www.simplifiedpython.net/python-chatbot/

## Tasks
- [x] Research blogs documenting chatbot implementation
- [x] Note the Python libraries / complete GitHub projects used
- [x] Suggest a possible way of how to implement this functionality
- [x] Create atomic issues which incrementally lead to a successful build
