### ISSUE TITLE
[RESEARCH] Python framework

### ISSUE THREAD

**Issue by h0nz1n** [lindamotejl/Secure-Application-Dev#8]
This issue will hold details regarding research and evaluation of potential usage of Python based Full-Stack / Micro framework environments.

## Detailed Description
A web framework is a software entity that is used to build web applications, holding the client-side and server-side programming contents. The server-side takes in the databases and its particular controls, while the client-side takes in the GUI elements.

## Context
Since the web framework implies a standard procedure in developing websites, we should seriously consider using it for both front-end and back-end development, instead of developing and putting together individual functionalities by ourselves.

## Research resources
https://medium.com/front-end-weekly/top-10-python-frameworks-in-2020-b0b6e61a592a
https://www.netsolutions.com/insights/top-10-python-frameworks-for-web-development-in-2019/

## Possible Implementation
https://www.djangoproject.com/
https://flask.palletsprojects.com/en/1.1.x/
http://web2py.com/
https://cherrypy.org/

## Tasks
- [x] Research and evaluate some of the Top10 Python frameworks for web development
- [x] Discuss the usage with lecturer
- [x] Prepare a dev server and install the chosen framework
